import getpass
import telnetlib
from tkinter import *
from tkinter.ttk import Labelframe
root=Tk()
root.title('Extract Config -From Network Devices!')
root.geometry("400x500")
labelip=Label(root,text="HOST IP ADDRESS")
labelip.pack(padx=10,pady=10)
hostip=Entry(root,width=50,font=('Helvetica',30))
hostip.pack(padx=10,pady=10)
labelusername=Label(root,text='USER NAME')
labelusername.pack(padx=10,pady=10)
username=Entry(root,width=50,font=('Helvetica',30))
username.pack(padx=10,pady=10)
labelfilename=Label(root,text='FILE NAME')
labelfilename.pack(padx=10,pady=10)
filename=Entry(root,width=50,font=('Helvetica',30))
filename.pack(padx=10,pady=10)
labelenabpass=Label(root,text="ENABLE PASSWORD")
labelenabpass.pack(padx=10,pady=10)
enable_password=Entry(root,width=50,font=('Helvetica',30))
enable_password.pack(padx=10,pady=10)
labellocalpass=Label(root,text="LOCAL PASSWORD")
labellocalpass.pack(padx=10,pady=10)
local_password=Entry(root,width=50,font=('Helvetica',30))
local_password.pack(padx=10,pady=10)
def myclick():
    HOST=hostip.get()
    username1=username.get()
    local_password1=local_password.get()
    enable_password1=enable_password.get()
    tn=telnetlib.Telnet(HOST)
    filename1=filename.get()
    tn.read_until(b"Username: ")
    tn.write(username1.encode('ascii')+b"\n")
    if local_password1:
	    tn.read_until(b"Password: ")
    tn.write(local_password.encode('ascii')+b"\n")
    tn.write(b"terminal length 0\n")
    tn.write(b"enable\n")
    tn.write(enable_password.encode('ascii')+b"\n")
    tn.write(b"show run\n")
    tn.write(b"exit\n")
    tn.write(b"exit\n")
    config=tn.read_all().decode('ascii')
    file=open(filename,'w')
    with open(filename.encode('ascii'),'w') as file:
            file.write(config)
myButton=Button(root,text="Back Up Config",command=myclick)
myButton.pack(pady=10)
root.mainloop()
